data:
  dataset: imagenet
  root: ./data/imagenet
  downsample: true
  
  train_split: train
  val_split: val

  batch_size: 16
  num_workers: 12

model:
  resnet:
    arch: resnet50

  branch_enc:
    embd_dim: 256
    out_dim: 128
    n_heads: 4
    n_layers: 5
    attn_pdrop: 0.1
    proj_pdrop: 0.1
    path_pdrop: 0.1
    eos: false
    embd_type: 0
    pe_type: 0

  content_enc:
    out_dim: 128
    arch: resnet10_imagenet

  branch_vae:
    hid_dim: 64
    n_layers: 3
    latent_dim: 4

opt:
  epochs: 9
  warmup_epochs: 1
  warmup: [branch_enc, content_enc]

  branch_enc:
    optim_type: adamw
    lr: 1.e-3
    weight_decay: 0.05
    sched_type: cosine

  content_enc:
    optim_type: adamw
    lr: 1.e-3
    weight_decay: 0.05
    sched_type: cosine

  branch_vae:
    optim_type: adam
    lr: 1.e-3
    weight_decay: 0
    sched_type: multistep
    steps: [8]
    gamma: 0.1

  clip_grad_norm: 1.0

train:
  n_branches: 64
  k: 1
  min_n_positives: 8
  temperature: 10

  delta_rs: 0.5
  rank_weight: 1.0
  sort_weight: 0.0
  bce_weight: 0.0

  vae_batch_size: 128

eval:
  n_branches: 4096
  max_macs: 1
  batch_size: 256